version: 2

updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "external"
    schedule:
      interval: "daily"
    # This may become too noisy if we start picking up untagged commits.
    # Watch https://github.com/dependabot/dependabot-core/issues/1639.
