version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"

  - package-ecosystem: "gitsubmodule"
    directory: "external"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat"
    # This may become too noisy if we start picking up untagged commits.
    # Watch https://github.com/dependabot/dependabot-core/issues/1639.

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
