on: [push]

name: Tests

jobs:
  coverage:
    name: Self tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust_version: [1.44.0, 1.46.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_version }}
          override: true

      - name: Run self tests
        uses: actions-rs/cargo@v1
        with:
          command: test
